# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from forge.proto_gen.forge.v1 import adapter_pb2 as forge_dot_v1_dot_adapter__pb2
from forge.proto_gen.forge.v1 import adapter_service_pb2 as forge_dot_v1_dot_adapter__service__pb2
from forge.proto_gen.forge.v1 import contextual_record_pb2 as forge_dot_v1_dot_contextual__record__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in forge/v1/adapter_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdapterServiceStub(object):
    """---------------------------------------------------------------------------
    AdapterService — the hub ↔ spoke contract
    ---------------------------------------------------------------------------

    ── Control plane ──────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/forge.v1.AdapterService/Register',
                request_serializer=forge_dot_v1_dot_adapter__service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=forge_dot_v1_dot_adapter__service__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/forge.v1.AdapterService/Configure',
                request_serializer=forge_dot_v1_dot_adapter__service__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=forge_dot_v1_dot_adapter__service__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/forge.v1.AdapterService/Start',
                request_serializer=forge_dot_v1_dot_adapter__service__pb2.StartRequest.SerializeToString,
                response_deserializer=forge_dot_v1_dot_adapter__service__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/forge.v1.AdapterService/Stop',
                request_serializer=forge_dot_v1_dot_adapter__service__pb2.StopRequest.SerializeToString,
                response_deserializer=forge_dot_v1_dot_adapter__service__pb2.StopResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/forge.v1.AdapterService/Health',
                request_serializer=forge_dot_v1_dot_adapter__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=forge_dot_v1_dot_adapter__pb2.AdapterHealth.FromString,
                _registered_method=True)
        self.Ingest = channel.stream_unary(
                '/forge.v1.AdapterService/Ingest',
                request_serializer=forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.SerializeToString,
                response_deserializer=forge_dot_v1_dot_adapter__service__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.Collect = channel.unary_stream(
                '/forge.v1.AdapterService/Collect',
                request_serializer=forge_dot_v1_dot_adapter__service__pb2.CollectRequest.SerializeToString,
                response_deserializer=forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/forge.v1.AdapterService/Subscribe',
                request_serializer=forge_dot_v1_dot_adapter__service__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/forge.v1.AdapterService/Unsubscribe',
                request_serializer=forge_dot_v1_dot_adapter__service__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=forge_dot_v1_dot_adapter__service__pb2.UnsubscribeResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/forge.v1.AdapterService/Write',
                request_serializer=forge_dot_v1_dot_adapter__service__pb2.WriteRequest.SerializeToString,
                response_deserializer=forge_dot_v1_dot_adapter__service__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Backfill = channel.unary_stream(
                '/forge.v1.AdapterService/Backfill',
                request_serializer=forge_dot_v1_dot_adapter__service__pb2.BackfillRequest.SerializeToString,
                response_deserializer=forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.FromString,
                _registered_method=True)
        self.Discover = channel.unary_unary(
                '/forge.v1.AdapterService/Discover',
                request_serializer=forge_dot_v1_dot_adapter__service__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=forge_dot_v1_dot_adapter__service__pb2.DiscoverResponse.FromString,
                _registered_method=True)


class AdapterServiceServicer(object):
    """---------------------------------------------------------------------------
    AdapterService — the hub ↔ spoke contract
    ---------------------------------------------------------------------------

    ── Control plane ──────────────────────────────────────────────────────
    """

    def Register(self, request, context):
        """Register a new adapter with the hub. Returns session_id on success.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Configure the adapter with connection parameters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Begin active operation (connect to source, start polling/subscribing).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Graceful shutdown — flush buffers, close connections.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Return current health status. Called periodically by hub.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ingest(self, request_iterator, context):
        """── Data plane ─────────────────────────────────────────────────────────

        Spoke pushes collected ContextualRecords to hub for ingestion.
        Client-streaming: spoke sends a stream of records, hub returns summary.
        adapter_id and session_id are passed via gRPC metadata headers:
        x-forge-adapter-id, x-forge-session-id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Collect(self, request, context):
        """Hub requests records from spoke (pull model). Server-streaming.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe to real-time value changes. Server-streaming.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Cancel an active subscription.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """── Capability RPCs (conditional on manifest) ──────────────────────────

        Write a value back to the source system (WritableAdapter).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Backfill(self, request, context):
        """Retrieve historical records for a time range (BackfillProvider).
        Server-streaming for large result sets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Discover(self, request, context):
        """List available tags/points in the source system (DiscoveryProvider).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdapterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=forge_dot_v1_dot_adapter__service__pb2.RegisterRequest.FromString,
                    response_serializer=forge_dot_v1_dot_adapter__service__pb2.RegisterResponse.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=forge_dot_v1_dot_adapter__service__pb2.ConfigureRequest.FromString,
                    response_serializer=forge_dot_v1_dot_adapter__service__pb2.ConfigureResponse.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=forge_dot_v1_dot_adapter__service__pb2.StartRequest.FromString,
                    response_serializer=forge_dot_v1_dot_adapter__service__pb2.StartResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=forge_dot_v1_dot_adapter__service__pb2.StopRequest.FromString,
                    response_serializer=forge_dot_v1_dot_adapter__service__pb2.StopResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=forge_dot_v1_dot_adapter__service__pb2.HealthRequest.FromString,
                    response_serializer=forge_dot_v1_dot_adapter__pb2.AdapterHealth.SerializeToString,
            ),
            'Ingest': grpc.stream_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.FromString,
                    response_serializer=forge_dot_v1_dot_adapter__service__pb2.IngestResponse.SerializeToString,
            ),
            'Collect': grpc.unary_stream_rpc_method_handler(
                    servicer.Collect,
                    request_deserializer=forge_dot_v1_dot_adapter__service__pb2.CollectRequest.FromString,
                    response_serializer=forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=forge_dot_v1_dot_adapter__service__pb2.SubscribeRequest.FromString,
                    response_serializer=forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=forge_dot_v1_dot_adapter__service__pb2.UnsubscribeRequest.FromString,
                    response_serializer=forge_dot_v1_dot_adapter__service__pb2.UnsubscribeResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=forge_dot_v1_dot_adapter__service__pb2.WriteRequest.FromString,
                    response_serializer=forge_dot_v1_dot_adapter__service__pb2.WriteResponse.SerializeToString,
            ),
            'Backfill': grpc.unary_stream_rpc_method_handler(
                    servicer.Backfill,
                    request_deserializer=forge_dot_v1_dot_adapter__service__pb2.BackfillRequest.FromString,
                    response_serializer=forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.SerializeToString,
            ),
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=forge_dot_v1_dot_adapter__service__pb2.DiscoverRequest.FromString,
                    response_serializer=forge_dot_v1_dot_adapter__service__pb2.DiscoverResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forge.v1.AdapterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forge.v1.AdapterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdapterService(object):
    """---------------------------------------------------------------------------
    AdapterService — the hub ↔ spoke contract
    ---------------------------------------------------------------------------

    ── Control plane ──────────────────────────────────────────────────────
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.v1.AdapterService/Register',
            forge_dot_v1_dot_adapter__service__pb2.RegisterRequest.SerializeToString,
            forge_dot_v1_dot_adapter__service__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.v1.AdapterService/Configure',
            forge_dot_v1_dot_adapter__service__pb2.ConfigureRequest.SerializeToString,
            forge_dot_v1_dot_adapter__service__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.v1.AdapterService/Start',
            forge_dot_v1_dot_adapter__service__pb2.StartRequest.SerializeToString,
            forge_dot_v1_dot_adapter__service__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.v1.AdapterService/Stop',
            forge_dot_v1_dot_adapter__service__pb2.StopRequest.SerializeToString,
            forge_dot_v1_dot_adapter__service__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.v1.AdapterService/Health',
            forge_dot_v1_dot_adapter__service__pb2.HealthRequest.SerializeToString,
            forge_dot_v1_dot_adapter__pb2.AdapterHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ingest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/forge.v1.AdapterService/Ingest',
            forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.SerializeToString,
            forge_dot_v1_dot_adapter__service__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Collect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/forge.v1.AdapterService/Collect',
            forge_dot_v1_dot_adapter__service__pb2.CollectRequest.SerializeToString,
            forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/forge.v1.AdapterService/Subscribe',
            forge_dot_v1_dot_adapter__service__pb2.SubscribeRequest.SerializeToString,
            forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.v1.AdapterService/Unsubscribe',
            forge_dot_v1_dot_adapter__service__pb2.UnsubscribeRequest.SerializeToString,
            forge_dot_v1_dot_adapter__service__pb2.UnsubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.v1.AdapterService/Write',
            forge_dot_v1_dot_adapter__service__pb2.WriteRequest.SerializeToString,
            forge_dot_v1_dot_adapter__service__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Backfill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/forge.v1.AdapterService/Backfill',
            forge_dot_v1_dot_adapter__service__pb2.BackfillRequest.SerializeToString,
            forge_dot_v1_dot_contextual__record__pb2.ContextualRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.v1.AdapterService/Discover',
            forge_dot_v1_dot_adapter__service__pb2.DiscoverRequest.SerializeToString,
            forge_dot_v1_dot_adapter__service__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
