"""AlarmDetector — monitors tag values and evaluates alarm conditions.

Sits between the Tag Engine (source of live values) and the AlarmEngine
(state machine + journal).  Supports:
- Threshold alarms (HI, HIHI, LO, LOLO) with deadband
- Digital alarms (state-change on boolean tags)
- Rate-of-change alarms (ROC on analog values)
- Quality alarms (tag quality degradation)
- Communication alarms (PLC connection loss)
- Delay timers (condition must persist N seconds before triggering)
"""

from __future__ import annotations

import asyncio
import logging
import time
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any

from forge.modules.ot.alarming.models import (
    AlarmConfig,
    AlarmEvent,
    AlarmType,
    ThresholdConfig,
)
from forge.modules.ot.alarming.engine import AlarmEngine

logger = logging.getLogger("forge.alarm.detector")


# ---------------------------------------------------------------------------
# Rate-of-change tracker
# ---------------------------------------------------------------------------


@dataclass
class _RocState:
    """Tracks previous values for rate-of-change detection."""

    last_value: float | None = None
    last_time: float | None = None


# ---------------------------------------------------------------------------
# Delay timer state
# ---------------------------------------------------------------------------


@dataclass
class _DelayState:
    """Tracks when a condition first became true for delayed alarms."""

    first_true_at: float | None = None
    fired: bool = False


# ---------------------------------------------------------------------------
# AlarmDetector
# ---------------------------------------------------------------------------


class AlarmDetector:
    """Evaluates incoming tag values against alarm configurations.

    The detector runs as a passive processor — call ``evaluate()`` each
    time a tag value changes.  It handles:

    1. Simple threshold evaluation (delegated to AlarmEngine.process_tag_value)
    2. Rate-of-change calculation and alarm triggering
    3. Delay timers (condition must persist before triggering)
    4. Communication alarm tracking

    Usage::

        detector = AlarmDetector(engine)

        # When a tag value arrives from the Tag Engine:
        events = await detector.evaluate("WH/WHK01/.../TIT_2010/Out_PV", 185.5)

        # When a PLC connection drops:
        events = await detector.report_comm_failure("PLC-01", "Connection timeout")

        # When a PLC connection is restored:
        events = await detector.report_comm_restore("PLC-01")
    """

    def __init__(self, engine: AlarmEngine) -> None:
        self._engine = engine

        # Rate-of-change state per tag_path
        self._roc_state: dict[str, _RocState] = defaultdict(_RocState)

        # Delay timer state per (tag_path, alarm_type)
        self._delay_state: dict[str, _DelayState] = defaultdict(_DelayState)

        # Communication alarm tracking: device_id → alarm_id
        self._comm_alarms: dict[str, str] = {}

    async def evaluate(
        self,
        tag_path: str,
        value: Any,
        quality: str = "GOOD",
    ) -> list[AlarmEvent]:
        """Evaluate a tag value against all configured alarms.

        Args:
            tag_path: Full tag path.
            value: Current tag value.
            quality: Tag quality (GOOD, BAD, UNCERTAIN, etc.).

        Returns:
            List of alarm events generated by this evaluation.
        """
        config = await self._engine.get_config(tag_path)
        if config is None or not config.enabled:
            return []

        events: list[AlarmEvent] = []

        # Rate-of-change alarms (must be checked before threshold)
        for threshold in config.thresholds:
            if threshold.alarm_type == AlarmType.RATE_OF_CHANGE:
                roc_events = await self._check_roc(config, threshold, value)
                events.extend(roc_events)

        # Delay checking for thresholds with delay_seconds > 0
        non_delayed = []
        for threshold in config.thresholds:
            if threshold.alarm_type == AlarmType.RATE_OF_CHANGE:
                continue  # Already handled above
            if threshold.delay_seconds > 0:
                delay_events = await self._check_with_delay(
                    config, threshold, value, quality
                )
                events.extend(delay_events)
            else:
                non_delayed.append(threshold)

        # Non-delayed thresholds — delegate to engine's built-in evaluation
        if non_delayed:
            engine_events = await self._engine.process_tag_value(
                tag_path, value, quality
            )
            events.extend(engine_events)

        return events

    async def report_comm_failure(
        self, device_id: str, detail: str = ""
    ) -> AlarmEvent | None:
        """Report a communication failure (PLC connection loss).

        Creates a COMMUNICATION alarm if one isn't already active for this device.
        """
        if device_id in self._comm_alarms:
            return None  # Already active

        alarm_id = await self._engine.trigger_alarm(
            name=f"COMM_FAIL:{device_id}",
            tag_path=f"_system/comm/{device_id}",
            priority="HIGH",
            value="DISCONNECTED",
            setpoint="CONNECTED",
            description=detail or f"Communication failure: {device_id}",
            area="",
            equipment_id=device_id,
            alarm_type=AlarmType.COMMUNICATION,
        )

        if alarm_id:
            self._comm_alarms[device_id] = alarm_id
            journal = await self._engine.get_alarm_history(limit=1)
            if journal:
                return AlarmEvent(**{
                    k: v for k, v in journal[0].items()
                    if k in AlarmEvent.__dataclass_fields__
                })
        return None

    async def report_comm_restore(self, device_id: str) -> bool:
        """Report a communication restoration. Clears the COMM alarm."""
        alarm_id = self._comm_alarms.pop(device_id, None)
        if alarm_id is None:
            return False
        return await self._engine.clear_alarm(alarm_id)

    # ------------------------------------------------------------------
    # Rate-of-change
    # ------------------------------------------------------------------

    async def _check_roc(
        self,
        config: AlarmConfig,
        threshold: ThresholdConfig,
        value: Any,
    ) -> list[AlarmEvent]:
        """Check rate-of-change alarm condition."""
        try:
            fval = float(value)
        except (TypeError, ValueError):
            return []

        now = time.monotonic()
        state = self._roc_state[config.tag_path]
        events: list[AlarmEvent] = []

        if state.last_value is not None and state.last_time is not None:
            dt = now - state.last_time
            if dt > 0:
                roc = abs(fval - state.last_value) / dt
                if roc >= threshold.setpoint:
                    alarm_id = await self._engine.trigger_alarm(
                        name=f"{config.tag_path}:ROC",
                        tag_path=config.tag_path,
                        priority=threshold.priority.value,
                        value=roc,
                        setpoint=threshold.setpoint,
                        description=threshold.description or f"Rate of change {roc:.2f}/s exceeds {threshold.setpoint}/s",
                        area=config.area,
                        equipment_id=config.equipment_id,
                        alarm_type=AlarmType.RATE_OF_CHANGE,
                    )
                    if alarm_id:
                        journal = await self._engine.get_alarm_history(limit=1)
                        if journal:
                            events.append(AlarmEvent(**{
                                k: v for k, v in journal[0].items()
                                if k in AlarmEvent.__dataclass_fields__
                            }))

        state.last_value = fval
        state.last_time = now
        return events

    # ------------------------------------------------------------------
    # Delay timer
    # ------------------------------------------------------------------

    async def _check_with_delay(
        self,
        config: AlarmConfig,
        threshold: ThresholdConfig,
        value: Any,
        quality: str,
    ) -> list[AlarmEvent]:
        """Check a threshold with delay_seconds persistence requirement."""
        key = f"{config.tag_path}:{threshold.alarm_type.value}"
        state = self._delay_state[key]

        condition_met = self._is_condition_met(threshold, value, quality)

        if condition_met:
            now = time.monotonic()
            if state.first_true_at is None:
                state.first_true_at = now
                return []

            elapsed = now - state.first_true_at
            if elapsed >= threshold.delay_seconds and not state.fired:
                state.fired = True
                # Condition persisted long enough — trigger via engine
                events = await self._engine.process_tag_value(
                    config.tag_path, value, quality
                )
                return events
        else:
            # Condition no longer met — reset timer
            if state.first_true_at is not None:
                state.first_true_at = None
                state.fired = False
                # Also try to clear via engine
                events = await self._engine.process_tag_value(
                    config.tag_path, value, quality
                )
                return events

        return []

    @staticmethod
    def _is_condition_met(
        threshold: ThresholdConfig, value: Any, quality: str
    ) -> bool:
        """Check if the raw threshold condition is met (ignoring delay)."""
        if threshold.alarm_type == AlarmType.QUALITY:
            return quality != "GOOD"

        if threshold.alarm_type == AlarmType.DIGITAL:
            return bool(value)

        try:
            fval = float(value)
        except (TypeError, ValueError):
            return False

        if threshold.alarm_type in (AlarmType.HI, AlarmType.HIHI):
            return fval >= threshold.setpoint
        if threshold.alarm_type in (AlarmType.LO, AlarmType.LOLO):
            return fval <= threshold.setpoint

        return False
